### ISSUE TITLE
拍照出来的图片可以压过在存进文件夹吗

### ISSUE THREAD

**Issue by ppg408331701** [haibuzou/WeixinPic#1]
现在拍照出来的图片会存到getSDCardRootPath设置的目录下,但是有点大,基本和不压缩一样,导致APP的缓存的数据很大,有什么办法可以把图片压缩小了再放进去

**Comment by haibuzou** [comment]
@ppg408331701 拍完照片后会显示照片，显示类是ShowImageActivity，其中显示之前对bitmap进行了压缩操作，再进行显示，但是本地的拍出来的照片并没有处理，如果你想处理的话，可以将压缩后的bitmap转为本地文件，再将压缩后的path返回。返回的方法在initEvent() 中
